Script started on 2015年03月10日 (週二) 17時37分18秒
]0;F74031140@2015cpp: ~F74031140@2015cpp:~$ whoami;pwd
F74031140
/home/F74031140
]0;F74031140@2015cpp: ~F74031140@2015cpp:~$ git config -l
]0;F74031140@2015cpp: ~F74031140@2015cpp:~$ git clone https://github.com/<your github account>/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gits/lab1.gitt/lab1.gite/lab1.gitv/lab1.gite/lab1.gitn/lab1.git8/lab1.git4/lab1.git1/lab1.git2/lab1.git1/lab1.git3/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74031140@2015cpp: ~F74031140@2015cpp:~$ exit

Script done on 2015年03月10日 (週二) 17時38分10秒
